export class Farmer_db{
    FramGuid: string;
    tyshxydm: string;
    address: string;
    jgdmUrl: string;
    FramType: string;
    cwName: string;
    FramName: string;
    FramTel: string;
    FramPeopleID: string;
    addr: string;
    FramBank: string;
    branch: string;
    FramIDFontUrl: string;
    FramIDBackUrl: string;
    BankCardUrl: string;
    fyzgzUrl: string;
    GPS: string;
    Remarks: string;
    createtime: string;
    dispute: string;
    management: string;
    percent: string;
    relationship: string;
    endtime: string;
    starttime: string;
    insurancepro: string;
    insuranceproname: string;
    insurancetype: string;
    policysignaUrl: string;
    housesignaUrl: string;
    isAllSigna: string;
    isHouseSigna: string;
    farmsmessage: string;
    banknum: string;
    isPass: string;
    noPassReason: string;
    insuranceId: string;
    HandlePerson: string;

    constructor() {
        this.FramGuid = "";
        this.tyshxydm = "";
        this.address = "";
        this.jgdmUrl = "";
        this.FramType = "";
        this.cwName = "";
        this.FramName = "";
        this.FramTel = "";
        this.FramPeopleID = "";
        this.addr = "";
        this.FramBank = "";
        this.branch = "";
        this.FramIDFontUrl = "";
        this.FramIDBackUrl = "";
        this.BankCardUrl = "";
        this.fyzgzUrl = "";
        this.GPS = "";
        this.Remarks = "";
        this.createtime = "";
        this.dispute = "";
        this.management = "";
        this.percent = "";
        this.relationship = "";
        this.endtime = "";
        this.starttime = "";
        this.insurancepro = "";
        this.insuranceproname = "";
        this.insurancetype = "";
        this.policysignaUrl = "";
        this.housesignaUrl = "";
        this.isAllSigna = "";
        this.isHouseSigna = "";
        this.farmsmessage = "";
        this.banknum = "";
        this.isPass = "";
        this.noPassReason = "";
        this.insuranceId = "";
        this.HandlePerson = "";
    }
}
