"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.DATA_TABLE = {
    //申报承保录入农户信息的表
    inframmessage: [
        { name: 'FramGuid', type: 'text', ISNull: 'NOT NULL' },
        { name: 'tyshxydm', type: 'text', ISNull: '' },
        { name: 'address', type: 'text', ISNull: '' },
        { name: 'jgdmUrl', type: 'text', ISNull: '' },
        { name: 'FramType', type: 'text', ISNull: 'NOT NULL' },
        { name: 'cwName', type: 'text', ISNull: '' },
        { name: 'FramName', type: 'text', ISNull: '' },
        { name: 'FramTel', type: 'text', ISNull: '' },
        { name: 'FramPeopleID', type: 'text', ISNull: '' },
        { name: 'addr', type: 'text', ISNull: '' },
        { name: 'FramBank', type: 'text', ISNull: '' },
        { name: 'branch', type: 'text', ISNull: '' },
        { name: 'FramIDFontUrl', type: 'text', ISNull: '' },
        { name: 'FramIDBackUrl', type: 'text', ISNull: '' },
        { name: 'BankCardUrl', type: 'text', ISNull: '' },
        { name: 'fyzgzUrl', type: 'text', ISNull: '' },
        { name: 'GPS', type: 'text', ISNull: 'NOT NULL' },
        { name: 'Remarks', type: 'text', ISNull: '' },
        { name: 'createtime', type: 'text', ISNull: 'NOT NULL' },
        { name: 'dispute', type: 'text', ISNull: 'NOT NULL' },
        { name: 'management', type: 'text', ISNull: 'NOT NULL' },
        { name: 'percent', type: 'text', ISNull: '' },
        { name: 'relationship', type: 'text', ISNull: 'NOT NULL' },
        { name: 'endtime', type: 'text', ISNull: 'NOT NULL' },
        { name: 'starttime', type: 'text', ISNull: 'NOT NULL' },
        { name: 'insurancepro', type: 'text', ISNull: 'NOT NULL' },
        { name: 'insuranceproname', type: 'text', ISNull: 'NOT NULL' },
        { name: 'insurancetype', type: 'text', ISNull: 'NOT NULL' },
        { name: 'policysignaUrl', type: 'text', ISNull: '' },
        { name: 'housesignaUrl', type: 'text', ISNull: '' },
        { name: 'isAllSigna', type: 'text', ISNull: '' },
        { name: 'isHouseSigna', type: 'text', ISNull: '' },
        { name: 'farmsmessage', type: 'text', ISNull: '' },
        { name: 'banknum', type: 'text', ISNull: '' }
    ],
    //申报承保信息的表
    Underwriting: [
        { name: 'FramGuid', type: 'text', ISNull: 'NOT NULL' },
        { name: 'SelfGuid', type: 'text', ISNull: 'NOT NULL' },
        { name: 'FramPeopleId', type: 'text', ISNull: 'NOT NULL' },
        { name: 'AnimalId', type: 'text', ISNull: 'NOT NULL' },
        { name: 'AnimalType', type: 'text', ISNull: 'NOT NULL' },
        { name: 'Varieties', type: 'text', ISNull: 'NOT NULL' },
        { name: 'AnimalAge', type: 'text', ISNull: '' },
        { name: 'AnimalWeight', type: 'text', ISNull: '' },
        { name: 'SelfPayPremium', type: 'text', ISNull: 'NOT NULL' },
        { name: 'TotalPremium', type: 'text', ISNull: 'NOT NULL' },
        { name: 'breedType', type: 'text', ISNull: 'NOT NULL' },
        { name: 'ImplantationSiteUrl', type: 'text', ISNull: 'NOT NULL' },
        { name: 'PositiveUrl', type: 'text', ISNull: 'NOT NULL' },
        { name: 'LeftUrl', type: 'text', ISNull: 'NOT NULL' },
        { name: 'RightUrl', type: 'text', ISNull: 'NOT NULL' },
        { name: 'GPS', type: 'text', ISNull: 'NOT NULL' },
        { name: 'OtherPicUrl', type: 'text', ISNull: '' },
        { name: 'createtime', type: 'text', ISNull: 'NOT NULL' },
        { name: 'Insuredamount', type: 'text', ISNull: 'NOT NULL' },
        { name: 'rate', type: 'text', ISNull: 'NOT NULL' },
        { name: 'Exemption', type: 'text', ISNull: '' },
        { name: 'parity', type: 'text', ISNull: '' },
        { name: 'breedadd', type: 'text', ISNull: 'NOT NULL' }
    ],
    //批量申报承保信息的表
    PiliangUnderwriting: [
        { name: 'FramGuid', type: 'text', ISNull: 'NOT NULL' },
        { name: 'SelfGuid', type: 'text', ISNull: 'NOT NULL' },
        { name: 'FramPeopleId', type: 'text', ISNull: 'NOT NULL' },
        { name: 'StartAnimalIds', type: 'text', ISNull: 'NOT NULL' },
        { name: 'EndAnimalIds', type: 'text', ISNull: 'NOT NULL' },
        { name: 'AnimalType', type: 'text', ISNull: 'NOT NULL' },
        { name: 'Varieties', type: 'text', ISNull: 'NOT NULL' },
        { name: 'SelfPayPremium', type: 'text', ISNull: 'NOT NULL' },
        { name: 'TotalPremium', type: 'text', ISNull: 'NOT NULL' },
        { name: 'breedType', type: 'text', ISNull: 'NOT NULL' },
        { name: 'GPS', type: 'text', ISNull: 'NOT NULL' },
        { name: 'createtime', type: 'text', ISNull: 'NOT NULL' },
        { name: 'Insuredamount', type: 'text', ISNull: 'NOT NULL' },
        { name: 'rate', type: 'text', ISNull: 'NOT NULL' },
        { name: 'parity', type: 'text', ISNull: '' },
        { name: 'AnimalAge', type: 'text', ISNull: '' },
        { name: 'AnimalWeight', type: 'text', ISNull: '' },
        { name: 'Animals1Url', type: 'text', ISNull: 'NOT NULL' },
        { name: 'Animals2Url', type: 'text', ISNull: 'NOT NULL' },
        { name: 'Animals3Url', type: 'text', ISNull: 'NOT NULL' },
        { name: 'AnimalsotherUrl', type: 'text', ISNull: '' },
        { name: 'AnimalList', type: 'text', ISNull: 'NOT NULL' },
        { name: 'breedadd', type: 'text', ISNull: 'NOT NULL' }
    ],
    //批量申报承保时录入农户信息的表
    piliangframmessage: [
        { name: 'FramGuid', type: 'text', ISNull: 'NOT NULL' },
        { name: 'tyshxydm', type: 'text', ISNull: '' },
        { name: 'address', type: 'text', ISNull: '' },
        { name: 'jgdmUrl', type: 'text', ISNull: '' },
        { name: 'FramType', type: 'text', ISNull: 'NOT NULL' },
        { name: 'cwName', type: 'text', ISNull: '' },
        { name: 'FramName', type: 'text', ISNull: '' },
        { name: 'FramTel', type: 'text', ISNull: '' },
        { name: 'FramPeopleID', type: 'text', ISNull: '' },
        { name: 'addr', type: 'text', ISNull: '' },
        { name: 'FramBank', type: 'text', ISNull: '' },
        { name: 'branch', type: 'text', ISNull: '' },
        { name: 'FramIDFontUrl', type: 'text', ISNull: '' },
        { name: 'FramIDBackUrl', type: 'text', ISNull: '' },
        { name: 'BankCardUrl', type: 'text', ISNull: '' },
        { name: 'fyzgzUrl', type: 'text', ISNull: '' },
        { name: 'GPS', type: 'text', ISNull: 'NOT NULL' },
        { name: 'Remarks', type: 'text', ISNull: '' },
        { name: 'createtime', type: 'text', ISNull: 'NOT NULL' },
        { name: 'dispute', type: 'text', ISNull: 'NOT NULL' },
        { name: 'management', type: 'text', ISNull: 'NOT NULL' },
        { name: 'percent', type: 'text', ISNull: '' },
        { name: 'relationship', type: 'text', ISNull: 'NOT NULL' },
        { name: 'endtime', type: 'text', ISNull: 'NOT NULL' },
        { name: 'starttime', type: 'text', ISNull: 'NOT NULL' },
        { name: 'insurancepro', type: 'text', ISNull: 'NOT NULL' },
        { name: 'insuranceproname', type: 'text', ISNull: 'NOT NULL' },
        { name: 'insurancetype', type: 'text', ISNull: 'NOT NULL' },
        { name: 'policysignaUrl', type: 'text', ISNull: '' },
        { name: 'housesignaUrl', type: 'text', ISNull: '' },
        { name: 'isAllSigna', type: 'text', ISNull: '' },
        { name: 'isHouseSigna', type: 'text', ISNull: '' },
        { name: 'farmsmessage', type: 'text', ISNull: '' },
        { name: 'banknum', type: 'text', ISNull: '' }
    ],
    //下载农户信息的表
    DnowLoadFarmData: [
        { name: 'FramGuid', type: 'text', ISNull: 'NOT NULL' },
        { name: 'InsureType', type: 'text', ISNull: 'NOT NULL' },
        { name: 'VaccinationCertificateImg', type: 'text', ISNull: 'NOT NULL' },
        { name: 'Address', type: 'text', ISNull: 'NOT NULL' },
        { name: 'BankAccount', type: 'text', ISNull: 'NOT NULL' },
        { name: 'ContactMail', type: 'text', ISNull: 'NOT NULL' },
        { name: 'ContactPerson', type: 'text', ISNull: 'NOT NULL' },
        { name: 'ContactTel', type: 'text', ISNull: 'NOT NULL' },
        { name: 'CreditCode', type: 'text', ISNull: 'NOT NULL' },
        { name: 'InstitutionCodeImg', type: 'text', ISNull: 'NOT NULL' },
        { name: 'isXubao', type: 'text', ISNull: 'NOT NULL' },
        { name: 'FramName', type: 'text', ISNull: 'NOT NULL' },
        { name: 'CreateTime', type: 'text', ISNull: 'NOT NULL' },
        { name: 'FramBank', type: 'text', ISNull: 'NOT NULL' },
        { name: 'FramLocation', type: 'text', ISNull: 'NOT NULL' },
        { name: 'FramPeopleID', type: 'text', ISNull: 'NOT NULL' },
        { name: 'FramTel', type: 'text', ISNull: 'NOT NULL' },
        { name: 'bankUrl', type: 'text', ISNull: 'NOT NULL' },
        { name: 'idbackUrl', type: 'text', ISNull: 'NOT NULL' },
        { name: 'idfrontUrl', type: 'text', ISNull: 'NOT NULL' },
        { name: 'signUrl', type: 'text', ISNull: 'NOT NULL' },
        { name: 'EndTime', type: 'text', ISNull: 'NOT NULL' },
        { name: 'InsureNo', type: 'text', ISNull: 'NOT NULL' }
    ],
    //下载承保信息的表
    DnowLoadUnderData: [
        { name: 'FramGuid', type: 'text', ISNull: 'NOT NULL' },
        { name: 'AnimalAge', type: 'text', ISNull: 'NOT NULL' },
        { name: 'AnimalId', type: 'text', ISNull: 'NOT NULL' },
        { name: 'AnimalType', type: 'text', ISNull: 'NOT NULL' },
        { name: 'FramLocation', type: 'text', ISNull: 'NOT NULL' },
        { name: 'FramPeopleID', type: 'text', ISNull: 'NOT NULL' },
        { name: 'SelfPayPremium', type: 'text', ISNull: 'NOT NULL' },
        { name: 'TotalPremium', type: 'text', ISNull: 'NOT NULL' },
        { name: 'Varieties', type: 'text', ISNull: 'NOT NULL' },
        { name: 'frontUrl', type: 'text', ISNull: 'NOT NULL' },
        { name: 'leftUrl', type: 'text', ISNull: 'NOT NULL' },
        { name: 'otherUrl', type: 'text', ISNull: 'NOT NULL' },
        { name: 'positonUrl', type: 'text', ISNull: 'NOT NULL' },
        { name: 'rightUrl', type: 'text', ISNull: 'NOT NULL' },
        { name: 'insurance', type: 'text', ISNull: 'NOT NULL' },
        { name: 'breedType', type: 'text', ISNull: 'NOT NULL' }
    ],
    //理赔表
    DeclareClaimTable: [
        { name: 'lhGuid', type: 'text', ISNull: 'NOT NULL' },
        { name: 'InstitutionCodeImg', type: 'text', ISNull: '' },
        { name: 'VaccinationCertificateImg', type: 'text', ISNull: 'NOT NULL' },
        { name: 'Bank', type: 'text', ISNull: 'NOT NULL' },
        { name: 'FramPeopleID', type: 'text', ISNull: '' },
        { name: 'CreditCode', type: 'text', ISNull: '' },
        { name: 'Address', type: 'text', ISNull: '' },
        { name: 'BankAccount', type: 'text', ISNull: '' },
        { name: 'ContactMail', type: 'text', ISNull: '' },
        { name: 'ContactTel', type: 'text', ISNull: '' },
        { name: 'AnimalId', type: 'text', ISNull: 'NOT NULL' },
        { name: 'DieMessage', type: 'text', ISNull: 'NOT NULL' },
        { name: 'FramIDFont', type: 'text', ISNull: '' },
        { name: 'FramIDBack', type: 'text', ISNull: '' },
        { name: 'BankCard', type: 'text', ISNull: 'NOT NULL' },
        { name: 'Scene', type: 'text', ISNull: 'NOT NULL' },
        { name: 'Harmless', type: 'text', ISNull: 'NOT NULL' },
        { name: 'ForDie', type: 'text', ISNull: 'NOT NULL' },
        { name: 'Other', type: 'text', ISNull: 'NOT NULL' },
        { name: 'GPS', type: 'text', ISNull: 'NOT NULL' },
        { name: 'Time', type: 'text', ISNull: 'NOT NULL' }
    ],
    //承保审核未通过的农户表
    FramNoPass: [
        { name: 'IID', type: 'text', ISNull: 'NOT NULL' },
        { name: 'Reason', type: 'text', ISNull: 'NOT NULL' },
        { name: 'FramName', type: 'text', ISNull: 'NOT NULL' },
        { name: 'FramTel', type: 'text', ISNull: 'NOT NULL' },
        { name: 'FramPeopleID', type: 'text', ISNull: 'NOT NULL' },
        { name: 'FramBank', type: 'text', ISNull: 'NOT NULL' },
        { name: 'FramLocation', type: 'text', ISNull: 'NOT NULL' },
        { name: 'idfrontUrl', type: 'text', ISNull: '' },
        { name: 'idbackUrl', type: 'text', ISNull: '' },
        { name: 'bankUrl', type: 'text', ISNull: 'NOT NULL' },
        { name: 'signUrl', type: 'text', ISNull: 'NOT NULL' },
        { name: 'VaccinationCertificateImg', type: 'text', ISNull: 'NOT NULL' },
        { name: 'InstitutionCodeImg', type: 'text', ISNull: '' },
        { name: 'CreateTime', type: 'text', ISNull: 'NOT NULL' },
    ],
    //承保审核未通过的承保表
    FramMessageNoPass: [
        { name: 'IID', type: 'text', ISNull: 'NOT NULL' },
        { name: 'Reason', type: 'text', ISNull: 'NOT NULL' },
        { name: 'FramIID', type: 'text', ISNull: 'NOT NULL' },
        { name: 'AnimalId', type: 'text', ISNull: 'NOT NULL' },
        { name: 'AnimalType', type: 'text', ISNull: 'NOT NULL' },
        { name: 'FramPeopleID', type: 'text', ISNull: 'NOT NULL' },
        { name: 'Varieties', type: 'text', ISNull: 'NOT NULL' },
        { name: 'AnimalAge', type: 'text', ISNull: 'NOT NULL' },
        { name: 'SelfPayPremium', type: 'text', ISNull: 'NOT NULL' },
        { name: 'TotalPremium', type: 'text', ISNull: 'NOT NULL' },
        { name: 'positonUrl', type: 'text', ISNull: 'NOT NULL' },
        { name: 'frontUrl', type: 'text', ISNull: 'NOT NULL' },
        { name: 'leftUrl', type: 'text', ISNull: 'NOT NULL' },
        { name: 'rightUrl', type: 'text', ISNull: 'NOT NULL' },
        { name: 'otherUrl', type: 'text', ISNull: 'NOT NULL' },
    ],
    //理赔审核未通过的理赔表
    FramLiPeiNoPass: [
        { name: 'IID', type: 'text', ISNull: 'NOT NULL' },
        { name: 'Reason', type: 'text', ISNull: 'NOT NULL' },
        { name: 'DieMessage', type: 'text', ISNull: 'NOT NULL' },
        { name: 'FramPeopleID', type: 'text', ISNull: 'NOT NULL' },
        { name: 'bankName', type: 'text', ISNull: 'NOT NULL' },
        { name: 'bankUrl', type: 'text', ISNull: 'NOT NULL' },
        { name: 'deathUrl', type: 'text', ISNull: 'NOT NULL' },
        { name: 'disposealUrl', type: 'text', ISNull: 'NOT NULL' },
        { name: 'idbackUrl', type: 'text', ISNull: 'NOT NULL' },
        { name: 'idfrontUrl', type: 'text', ISNull: 'NOT NULL' },
        { name: 'localUrl', type: 'text', ISNull: 'NOT NULL' },
        { name: 'otherImgs', type: 'text', ISNull: 'NOT NULL' },
        { name: 'pin', type: 'text', ISNull: 'NOT NULL' },
    ]
};
